/* Team Co-op Evaluation tables */

CREATE TABLE Employee(
	ID INT PRIMARY KEY NOT NULL,
	STUDENTID INT,
	FIRSTNAME TEXT,
	LASTNAME TEXT,
	EMAIL TEXT,
	DATECREATED DATE,
	LASTMODIFIED DATE,
	PERMISSIONS INT,
	FOREIGN KEY(STUDENTID) REFERENCES STUDENT(ID)
);

CREATE TRIGGER date_created AFTER INSERT ON Employee
BEGIN
	UPDATE Employee SET DATECREATED = Datetime('now') WHERE ROWID = NEW.ROWID;
END;

CREATE TRIGGER date_modified AFTER UPDATE ON Employee
BEGIN
	UPDATE Employee SET LASTMODIFIED = Datetime('now') WHERE ROWID = NEW.ROWID;
END;